-- MySQL Script generated by MySQL Workbench
-- Thu Sep 23 23:08:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema generador_horariosbd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema generador_horariosbd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `generador_horariosbd` DEFAULT CHARACTER SET utf8 ;
USE `generador_horariosbd` ;

-- -----------------------------------------------------
-- Table `generador_horariosbd`.`maestro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `generador_horariosbd`.`maestro` (
  `id` VARCHAR(255) NOT NULL,
  `nombres` VARCHAR(255) NOT NULL,
  `apellidos` VARCHAR(255) NOT NULL,
  `disponibilidad` VARCHAR(140) NOT NULL DEFAULT '00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
