/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capturaMaestros.interfase;

import capturaMaestros.variables.Maestro;
import capturaMaestros.variables.VectorMaestros;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author Alfredo Perez
 */
public class DialogNomMaestro2 extends javax.swing.JDialog {

    private AbsoluteLayout layaut = new AbsoluteLayout();
    JButton jButton1 = new JButton();
    JButton jButton2 = new JButton();
    JTextField jTextField1 = new JTextField();
    JTextField jTextField2 = new JTextField();
    JTextField jTextField3 = new JTextField();
    JLabel jLabel1 = new JLabel();
    JLabel jLabel2 = new JLabel();
    JLabel jLabel3 = new JLabel();

    Maestro maestroAux;
    VectorMaestros vector;
    /**
     * Creates new form DialogNomMaestro2
     */
    public DialogNomMaestro2(java.awt.Frame parent, boolean modal, VectorMaestros vecMaes) {
    super(parent, modal);
    vector=vecMaes;
    maestroAux=new Maestro();
    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    try {
      jbInit();
    }
    catch(Exception e) {
      e.printStackTrace();
    }
  }
  private void jbInit() throws Exception {
    this.getContentPane().setLayout(layaut);

    this.setSize(new Dimension(600,500));
    this.setTitle("NOMBRE DE MAESTROS");

    jButton1.setText("ACEPTAR");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(ActionEvent e) {
        jButton1_actionPerformed(e);
      }
    });


    jButton2.setText("SALIR");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(ActionEvent e) {
        jButton2_actionPerformed(e);
      }
    });

    jLabel1.setText("CLAVE");
    jLabel2.setText("NOMBRE");
    jLabel3.setText("APELLIDO");
    //xYLayout1.setWidth(426);
    //xYLayout1.setHeight(300);
    this.setCursor(null);
    this.setResizable(false);
    this.setModal(true);
    this.getContentPane().add(jTextField2, new AbsoluteConstraints(135, 114, 229, 30));
    this.getContentPane().add(jTextField3, new AbsoluteConstraints(135, 158, 229, 30));
    this.getContentPane().add(jLabel2, new AbsoluteConstraints(61, 112, 76, 30));
    this.getContentPane().add(jLabel3, new AbsoluteConstraints(61, 162, 82, 30));
    this.getContentPane().add(jButton1, new AbsoluteConstraints(61, 222, 133, 43));
    this.getContentPane().add(jButton2, new AbsoluteConstraints(227, 219, 136, 46));
    this.getContentPane().add(jLabel1, new AbsoluteConstraints(61, 61, 119, 30));
    this.getContentPane().add(jTextField1, new AbsoluteConstraints(135, 62, 101, 30));
  }

  void jButton1_actionPerformed(ActionEvent e) {
    System.out.println("Entra a boton1");
    String mensajeText1= jTextField1.getText();
     System.out.println("Probando string ID="+mensajeText1);
    int longitud = mensajeText1.length();
    try{
      maestroAux = new Maestro(jTextField1.getText(), jTextField2.getText(), jTextField3.getText());
      vector.addElement(maestroAux);
      /*if(maestroAux.isMaestroOk()){
        System.out.println("si esta OK");

        vector.addElement(maestroAux);
        //vector.copiarClavNom(maestroAux);

        this.dispose();
      }
      else{
        jTextField1.setText("");
      }*/
    }
    catch(Exception excp){
      jTextField1.setText("");
    }
    System.out.println("Sale de boton1");
  }

  void jButton2_actionPerformed(ActionEvent e) {
    this.dispose();
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
